### ISSUE TITLE
Practica 3 ARCHITEC

### ISSUE THREAD

**Issue by carlos-chrs** [SistemasTecTlaxiaco/practica-architect-carlos-chrs#1]
[Practica_architec_hernandez_matra_carlos_christian.pdf](https://github.com/SistemasTecTlaxiaco/practica-architect-carlos-chrs/files/7166669/Practica_architec_hernandez_matra_carlos_christian.pdf)

**Comment by Yabin-2021** [comment]
Muy buen trabajo...
Puntaje = **20 %**

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
